eleven-labs/blog.eleven-labs.com

Gemfile
Lock gem versions according to https://pages.github.com/versions/
=> chore(bundler): lock gem versions

.editorconfig
=> chore(editor): add editorconfig file

.travis.yml, Gemfile, Rakefile
=> chore(ci): init ci

_config.yml, _includes/icons.html, _sass/base/_variables.scss
=> feat: basic configuration

_sass/external/_syntax.scss
better style for syntax highlighting
=> feat(style): better syntax highlighting

_sass/base/_variables.scss
Match header bg-color with header image bg color
Use header bg-color complementary color for links
=> feat(style): header background color

.editorconfig
improve editor config
- alphabetical order
- max line length to 120 char
- trim trailing whitespace
=> chore(editor): improve editor config

_config.yml, _includes/disqus.html, _includes/footer.html, _includes/head.html, _includes/header.html, _includes/icons.html, _layouts/default.html, _layouts/page.html, _layouts/post.html, _sass/base/_global.scss, _sass/base/_utility.scss, _sass/external/_reset.scss, _sass/includes/_footer.scss, _sass/includes/_header.scss, _sass/layouts/_index.scss, _sass/layouts/_posts.scss, index.html
=> chore: checkstyle

_layouts/post.html
use author display name in post
=> feat(layout): use author display name in post

Gemfile, _config.yml, _includes/head.html
Better SEO with https://github.com/jekyll/jekyll-seo-tag
=> feat: better seo

_includes/reading_time.html, _layouts/post.html, index.html
Fixes https://github.com/eleven-labs/eleven-labs.github.io/issues/31
=> [#31] added reading time

_config.yml, _includes/head.html
J'ai fait le tour du seo, c'est parfait :)
J'ai juste fait une PR https://github.com/jekyll/jekyll-seo-tag/pull/213 pour ajouter l'image pour twitter qui n'est pas pas mandatory 
J'ai mis a jour deux metas
=> feat(seo): add meta seo 

_includes/links.html, _layouts/post.html
Mise en place de 3 liens sur chaque post
=> feat(links): display 3 links in all posts

.travis.yml, Gemfile, _config.yml, _includes/head.html, _includes/header.html, _layouts/default.html, js/moment.js, js/search.js
Mise en place du moteur de recherche algolia
=> feat(search): add search with algolia

_includes/footer.html
Changement du lien pour la newsletter
=> feat(newsletter): change link for newsletter

.travis.yml
Reverts eleven-labs/eleven-labs.github.io#83
=> Revert "feat: send to algolia only on master"

_posts/2015-11-12-pattern-state.md, _posts/2015-12-15-non-faire-de-la-veille-ce-nest-pas-lire-les-tutos-du-sdz.md, _posts/2017-03-09-retour-experience-codeception.md
Made the jekyll build fail in dev env
=> Fixed special chars in title and excerpt

_sass/external/_reset.scss
=> fix : increase code, kbd, pre and samp font from 1rem to 1.5rem

_sass/external/_syntax.scss
suppression du `wrap` sur les blocks de code
=> feat(ui): do not wrap on code blocks

_config.yml
Modification du footer sur demande de @ElevenTom
=> feat(footer): to inifinity and beyond !

404.html, 404.md
=> feat: New 404 error page

.travis.yml, Rakefile
remove script from travis configuration file to use Rakefile
=> feat(test): use rakefile for travis tests

_config.yml, index.html
=> feat(pagination) : Add pagination

Gemfile, _config.yml
- Config RSS (Atom)
- Add Rss Icon
Ref : #122
=> Add Rss icon + rss config (atom)

_config.yml
google a commencé à indexer le blog en https vu que c'est dans la config
ca pause problème avec les histoire de certificats github
je remet en http dans la config
=> fix(config): fix url https -> http

_layouts/author.html
=> feat(author) : Change label for author's latests articles

_includes/footer.html, _includes/newsletter_link.html, _layouts/author.html, _layouts/page.html, _layouts/post.html, index.html
=> feat(newsletter) : Moved newsletter link above on post page

_posts/2017-06-06-test.md
=> feat: add article test

_sass/layouts/_posts.scss
Centrage horizontal de l'image de cover des articles
=> feat(ui): center horizontal cover image

_posts/2017-07-19-video-live-dash-hls.md
Corrections de quelques fautes d'accents et consonnes en double, grâce à l’œil avisé de Martin :)
=> fix typo 2 (martin)

_includes/links.html, _layouts/post.html
=> feat(post) : Removed current post from the also read list

.editorconfig, Gemfile, Rakefile, _includes/head.html, _layouts/post.html, _sass/base/_global.scss, _sass/base/_utility.scss, _sass/external/_reset.scss, _sass/external/_syntax.scss, _sass/includes/_author.scss, _sass/includes/_footer.scss, _sass/includes/_header.scss, _sass/includes/_md-content.scss, _sass/layouts/_index.scss, _sass/layouts/_posts.scss, _sass/objects/_avatar.scss, _sass/objects/_buttons.scss, _sass/objects/_layout.scss, _sass/objects/_meta.scss, _sass/objects/_newsletter.scss, _sass/objects/_page-heading.scss, _sass/objects/_read-also.scss, _sass/objects/_search-bar.scss, _sass/settings/_fonts.scss, _sass/settings/_variables.scss, css/main.scss, manifest.json
Reverts eleven-labs/eleven-labs.github.io#175
=> Revert "feat(linting): Ajout du linting des fichiers .scss"

.editorconfig, Gemfile, Rakefile, _includes/head.html, _layouts/post.html, _sass/base/_global.scss, _sass/base/_utility.scss, _sass/external/_reset.scss, _sass/external/_syntax.scss, _sass/includes/_author.scss, _sass/includes/_footer.scss, _sass/includes/_header.scss, _sass/includes/_md-content.scss, _sass/layouts/_index.scss, _sass/layouts/_posts.scss, _sass/objects/_avatar.scss, _sass/objects/_buttons.scss, _sass/objects/_layout.scss, _sass/objects/_meta.scss, _sass/objects/_newsletter.scss, _sass/objects/_page-heading.scss, _sass/objects/_read-also.scss, _sass/objects/_search-bar.scss, _sass/settings/_fonts.scss, _sass/settings/_variables.scss, css/main.scss, manifest.json
Reverts eleven-labs/eleven-labs.github.io#177
=> Revert "Revert "feat(linting): Ajout du linting des fichiers .scss""

feed.xml
=> Fix empty title & description in rss feed

.travis.yml, _config.yml, bin/deploy-pr.sh, index.html
=> feat(deploy): deploy to AWS S3

.travis.yml
un oubli sur la PR précédente 😏
=> feat(travis,aws): enable cloudfront cli

_posts/2017-09-10-flux-infini-react-symfony.md
Reverts eleven-labs/eleven-labs.github.io#220
=> Revert "Update 2017-09-10-flux-infini-react-symfony.md"

_posts/2017-09-10-flux-infini-react-symfony.md
Reverts eleven-labs/eleven-labs.github.io#221
=> Revert "Revert "Update 2017-09-10-flux-infini-react-symfony.md""

.travis.yml
=> feat(deploy,s3): flush bucket before deploy

bin/deploy-pr.sh
some authors use the `_drafts` directoy when writing a post
the live preview now includes this directory during build step
=> feat(preview): also deploy drafts

_posts/2017-09-15-fastlane-ios.md
=> fix(post): missing author

_posts/2017-09-20-presentation-protocol-buffers.md
=> fix(post): front matter

Gemfile, _config.yml, _includes/amp.scss
Reverts eleven-labs/eleven-labs.github.io#242
=> Revert "feat: add amp"

Gemfile, Rakefile, _config.yml, _includes/amp.scss, _posts/2014-02-10-chrome-screencast-deboguer-le-rendu-mobile-dun-site-responsive.md
Reverts eleven-labs/eleven-labs.github.io#243
=> Revert "Revert "feat: add amp""

_posts/2017-10-09-openpgp-paire-clef-presque-parfaite-partie-1.md
* links are not clickable at end of article
* cover image is too fat
* fix some typo on command
=> Fix links on resource

Gemfile, _config.yml
Reverts eleven-labs/eleven-labs.github.io#278
algolia fail
https://travis-ci.org/eleven-labs/eleven-labs.github.io/builds/292540172
=> Revert "feat(gem): update jekyll, plugins & other gems"

Gemfile, _config.yml
Reverts eleven-labs/eleven-labs.github.io#283
=> feat(gem): update jekyll, plugins & other gems

_posts/2017-10-26-git-bisect.md
=> Misspell word

bin/deploy-pr.sh
=> feat(preview,s3): clean before upload to s3

_config.yml
exclude:
paths from algolia indexation
=> feat(config): add some algolia excluded paths

_config.yml
Pagination creates dumb url path like: `https://blog.eleven-labs.com/blog/page8/`
Update config to create path like: `https://blog.eleven-labs.com/page/8/`
=> feat(config): change pagination path

_posts/en/2017-11-09-build-an-api-with-go-and-buffalo.md
=> quentin en article

_includes/search.html, js/search.js
Fix wrong behaviour when pressing enter on search input
closes: #345
=> fix(search): Add event listener on form submit

_i18n/en.yml, _i18n/fr.yml, _includes/share.html
Fix: https://github.com/eleven-labs/blog.eleven-labs.com/issues/348
=> fix(share): fix wrong titles

bin/check-spelling.sh
spellcheck on master is useless and increase deployment time
=> fix(ci,cd,bin): no spellcheck on master

_includes/amp-icons.html, _includes/icons.html, _includes/scripts.html, _includes/share.html, js/track-links.js
Close: https://github.com/eleven-labs/blog.eleven-labs.com/issues/183
=> feat(links): add google analytics track of follow and share links

_includes/scripts.html, js/service-worker.js, manifest.json, sw.js
Ajout des notifications
Permet de recevoir dans un firebase les token des utilisateurs
=> feat: ajout des notificaitons

bin/deploy-pr.sh
=> feat(preview): build future posts in preview

_posts/fr/2017-12-19-push-notification.md, js/service-worker.js
Permet d'activer les notifications même si tu as deja le service worker d'intallé
=> feat: change subscribe every time when service worker exist

_includes/head.html
Utilisation de la bonne url pour le contenu AMP :)
=> fix: use good url for en amp

.travis.yml
Reverts eleven-labs/blog.eleven-labs.com#424
=> Revert "chore(ci): add slack message after master deploy"

.travis.yml, bin/notify-slack.sh
Reverts eleven-labs/blog.eleven-labs.com#425
=> Revert "Revert "chore(ci): add slack message after master deploy""

_includes/amp-icons.html, _includes/icons.html, _includes/share.html, js/cookie-consent.js
closes: #438 #436 #435 #434 #432
=> feat(tracking): improve event category granularity

_includes/newsletter_link.html
=> Added GA tracking to newsletter link

_authors/vdelpeyroux.md
=> change name file author

_posts/fr/2018-04-05-api-platform.md
=> fix wording

_posts/fr/2018-04-05-api-platform.md
This PR fixes some typo in the API-Platform post.
Thanks for talking about the framework!
=> meta: fix some typo

_sass/includes/_md-content.scss
fix https://github.com/eleven-labs/blog.eleven-labs.com/issues/446
=> style(h2): fix h2 which was inline

_posts/fr/2018-11-22-retour-sur-le-php-forum-2018.md
Bonjour,
je vous propose la correction de deux fautes de frappes que j'ai pu noter lors de la lecture de votre article sur le Forum PHP 2018.
=> Fix typo in Mysql paragraph of PHP Forum 2018 post

.travis.yml
does not rebuild before deployment on master
=> chore(travis): speed up deployment

.travis.yml, bin/deploy-pr.sh
also bugfix for PR deployment, because the AWS CLI was used to rm files in the wrong buckets
=> feat(ci): deploy using awscli instead of travis module

_authors/dsuarez.md
=> feat(author): update dsuarez author

_sass/layouts/_index.scss, _sass/settings/_variables.scss, index.html
Version desktop de la page articleS faite : 
- il faut tester le contenu de la page 
- Mon travail ne porte par sur le header / footer mais s'il y a des beugs je veux bien des retours quand même ;)
=> responsive desktop version for page articles

_includes/links.html, _layouts/author.html, _sass/includes/_author.scss
Page auteur, on a essayé de garder un design semblable à ce qui existait déjà étant donné qu'on avait pas de maquette pour cette partie
=> add some styling to the author page

_sass/layouts/_index.scss, index.html
Social icons will be used, commented for now
=> Changed link behavior & commented a future update

_sass/layouts/_posts.scss, _sass/objects/_meta.scss
Increased margin between meta__authors
=> Fixed an issue with Authors footer block when multiple authors

_includes/author_link.html, _includes/cookie_banner.html, _includes/header-variables.scss.liquid, _includes/header.html, _includes/newsletter_link.html, _includes/share.html, _sass/layouts/_index.scss
- corrige des erreurs de html (multiple h1 / balise br / div > li corrigés en ul > li)
- corrige des urls de partages qui contenaient des espaces
=> branch done to correct all W3C errors and SEO stuffs

_includes/head.html, _includes/header-variables.scss.liquid, _includes/header.html
Re Upload of header.scss.liquid from previous PR (mobile_site_access #601) after been modified due to a merge
=> back on erased changes during a merge

_layouts/author.html
Tester en allant voir sur le profil de Maeva
Puis celui de Pouzor / Jojo / Arnaud ou quelqu'un qui a une image.
=> do not display image container for author who don't have one

.travis.yml
=> chore(ci): cache bundler & rendering directory

_posts/en/2019-05-27-delegates-closures.md, _posts/fr/2016-12-28-delegates-closures.md, _posts/fr/2017-01-11-android-listeners.md, _posts/fr/2017-01-25-ios-comment-coupler-les-delegates-les-closures.md
Reverts eleven-labs/blog.eleven-labs.com#669
=> Revert "Revert "Feat/trad tibo""

_posts/en/2020-01-29-react-i18next.md
updated because of build logs
https://travis-ci.org/eleven-labs/blog.eleven-labs.com/builds/646334333#L397
=> fix(post): raw liquid for js block

_authors/fverneuil.md
- front matter indentation
- login sensitive case
=> Fix fverneuil author page

_posts/fr/2021-05-24-leco-conception.md
=> Article eco-conception fix youtube url

_posts/fr/2016-06-21-git-rebase.md, _posts/fr/2021-09-22-git-rebase.md
Edit date + Fix titles H1 + Add internal link + Fix categories
=> Maj Article

.github/workflows/audit-lighthouse.yml, .github/workflows/deploy.yml, .github/workflows/pr-closed.yml
> The `Audit Lighthouse` workflow does not launch until it's merged to the default branch
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
PR linked:
https://github.com/eleven-labs/blog.eleven-labs.com/pull/906
https://github.com/eleven-labs/blog.eleven-labs.com/pull/908
=> 💚 separate audit lighthouse into another workflow

src/helpers/indexationAlgoliaHelper.ts
https://github.com/eleven-labs/blog.eleven-labs.com/issues/983
=> fix: sort search by date

_posts/fr/2023-05-03-archi-modelisation.md
En lisant l'article j'ai vu qu'une des images ne passait plus, et 2 petites erreurs de typo ;)
=> fix article archi-modelisation img and typo

src/components/ArticleMetadata/ArticleMetadata.tsx, src/containers/HeaderContainer/useHeaderContainer.tsx, src/containers/LinkContainer/LinkContainer.tsx
- Warning: Each child in a list should have a unique key prop. in ArticleMetadata
- forwardRef missing in LinkContainer
- fix eslint warnings
=> fix: avoid react warnings

src/components/ArticleMetadata/ArticleMetadata.tsx, src/components/AutocompleteField/AutocompleteField.stories.tsx, src/components/AutocompleteField/AutocompleteResult/AutocompleteResult.tsx, src/components/PostPreview/PostPreview.stories.tsx, src/components/PostPreview/PostPreview.tsx, src/components/PostPreviewList/PostPreviewList.stories.tsx, src/components/PostPreviewList/PostPreviewList.tsx, src/components/TutorialSteps/TutorialSteps.tsx, src/containers/HeaderContainer/useHeaderContainer.tsx, src/pages/PostPage/RelatedPostList/RelatedPostList.tsx
fixes:
- https://github.com/eleven-labs/blog.eleven-labs.com/pull/1032/files#diff-a7bab80819f697dc984a2cf94484d74cf628ece71483f2c93a64d14e99a02ebaR50
- https://github.com/eleven-labs/blog.eleven-labs.com/pull/1026/files#diff-a7bab80819f697dc984a2cf94484d74cf628ece71483f2c93a64d14e99a02ebaR28
=> fix: react keys to avoid warnings and authors being mixed up

_articles/fr/2023-11-06-micro-frontend.md
fixes https://github.com/eleven-labs/blog.eleven-labs.com/pull/1027
=> fix: microfrontend article typos

_articles/fr/2023-11-14-rex-plateforme-data.md
feedback from https://github.com/eleven-labs/blog.eleven-labs.com/pull/988#pullrequestreview-1746081631
=> fix: apply feedback for rex data platforme

_articles/fr/2024-10-08-paris-web-2024.md
https://blog.staging.eleven-labs.com/feat/paris-web-2024/
=> feat: add article Paris Web 2024
